FROM mcr.microsoft.com/devcontainers/python:1-3.13

WORKDIR /devcontainers
COPY . /devcontainers/

# Setup a python virtual environment
RUN python3 -m venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"

# Install home assistant in the new virtual environment
RUN pip install homeassistant
