name: hacs-validate

on:
  push:
  workflow_dispatch:
  workflow_call:

permissions: {}

jobs:

  validate-hacs:
    runs-on: "ubuntu-latest"
    steps:
      -
        name: HACS validation
        uses: hacs/action@22.5.0
        with:
          category: integration
          ignore: brands images
