name: pr

on:
  pull_request:
    types:
      - synchronize
      - opened
      - reopened

permissions:
  contents: write
  id-token: write
  pull-requests: read
  packages: write

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  detect-changes:
    uses: ./.github/workflows/detect-changes.yml

  preview-hacs-validate:
    needs: detect-changes
    if: ${{ needs.detect-changes.outputs.hacs_json_changed == 'true' || needs.detect-changes.outputs.hacs_validate_changed == 'true' }}
    uses: ./.github/workflows/hacs-validate.yml
    secrets: inherit

  preview-version-update:
    needs: detect-changes
    if: ${{ needs.detect-changes.outputs.version_update_changed == 'true' }}
    uses: ./.github/workflows/version-update.yml
    with:
      dry-run: true
    secrets: inherit

  pr-ready:
    needs:
      - detect-changes
      - preview-hacs-validate
      - preview-version-update
    runs-on: ubuntu-latest
    if: always()
    steps:
      -
        name: Validate jobs
        if: ${{ contains(needs.*.result, 'cancelled') || contains(needs.*.result, 'failure') }}
        run: |
          echo "::error title=${{ github.workflow }}::at least one job failed or cancelled"
          exit 1
